# Site settings
title: An Awesome Place in Web Space
email: isislvx@github.com
description: > # this means to ignore newlines until "baseurl:"
  This is my new site description. Clearly, I am clueless on how to use this, but I will learn some day. Once I figure out how to update my metadata I will be golden.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
twitter_username: 
github_username:  isislvx
# Build settings
markdown: kramdown

defaults:
-
scope:
	path: ""
		type: "posts"
		values:
	layouts: "posts"	
	-
